# Generated by Django 4.2.7 on 2023-11-29 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trucks", "0002_alter_foodtruck_expiration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodtruck",
            name="x",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="y",
        ),
    ]
