# Generated by Django 4.2.7 on 2023-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trucks", "0003_remove_foodtruck_x_remove_foodtruck_y"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtruck",
            name="location_id",
            field=models.CharField(max_length=100),
        ),
    ]
