# Generated by Django 4.2.7 on 2023-11-29 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trucks", "0004_alter_foodtruck_location_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodtruck",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="dayshours",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="fire_prevention_districts",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="noi_sent",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="permit",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="police_districts",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="prior_permit",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="received",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="status",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="supervisor_districts",
        ),
    ]
