# Generated by Django 4.2.7 on 2023-11-29 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "trucks",
            "0005_remove_foodtruck_approved_remove_foodtruck_dayshours_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodtruck",
            name="cnn",
        ),
        migrations.RemoveField(
            model_name="foodtruck",
            name="neighborhoods",
        ),
    ]
