# Generated by Django 4.2.7 on 2023-11-29 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("trucks", "0006_remove_foodtruck_cnn_remove_foodtruck_neighborhoods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtruck",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
    ]
