# Generated by Django 4.2.7 on 2023-11-29 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trucks", "0007_alter_foodtruck_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodtruck",
            name="schedule_url",
        ),
    ]
